# =============================================================
# .woodpecker/ci.yml
# =============================================================

when:
  event: [push, pull_request]

steps:
  - name: ci-pipeline
    image: induzio-ci-runner:latest
    pull: false

    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      SENDGRID_API_KEY:
        from_secret: sendgrid_api_key

    commands:
      - bash /ci/scripts/entrypoint.sh
